using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Usagi.ToolCore.Audio;

public static partial class FsidBuilder
{
    public static string NormalizeSoundName(string enumName) =>
        enumName.Trim().Replace(' ', '_');

    public static uint ComputeSoundCrc(string enumName) =>
        Crc32.Compute(Encoding.UTF8.GetBytes(NormalizeSoundName(enumName)));

    public static string WriteHeader(AudioBank bank, string ifndefName, string enumName)
    {
        var entries = BuildEntries(bank);
        var builder = new StringBuilder();
        builder.Append("#ifndef ").Append(ifndefName).AppendLine();
        builder.Append("#define ").Append(ifndefName).AppendLine();
        builder.AppendLine();
        builder.AppendLine("// Generated by Usagi Audio Tool.");
        foreach (var entry in entries)
        {
            builder.Append("static const unsigned int ")
                .Append(entry.Name)
                .Append(" = ")
                .Append(entry.Crc.ToString(CultureInfo.InvariantCulture))
                .AppendLine(";");
        }

        builder.Append("static const unsigned int ")
            .Append(enumName)
            .Append("_COUNT = ")
            .Append(entries.Count.ToString(CultureInfo.InvariantCulture))
            .AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("#endif");
        return builder.ToString();
    }

    public static string WriteProto(AudioBank bank, string enumName, DateTimeOffset? generatedAt = null)
    {
        var entries = BuildEntries(bank);
        var timestamp = generatedAt ?? DateTimeOffset.Now;
        var protoEnumName = enumName.Trim().Replace(" ", "", StringComparison.Ordinal);
        var builder = new StringBuilder();
        builder.AppendLine("/****************************************************************************");
        builder.Append("//  Usagi Engine, Copyright (c) Vitei, Inc. ")
            .Append(timestamp.Year.ToString(CultureInfo.InvariantCulture))
            .AppendLine();
        builder.Append("//  Auto-generated by Usagi Audio Tool at ")
            .Append(timestamp.LocalDateTime.ToString(CultureInfo.CurrentCulture))
            .AppendLine();
        builder.AppendLine("****************************************************************************/");
        builder.AppendLine();
        builder.AppendLine();
        builder.AppendLine("import 'nanopb.proto';");
        builder.AppendLine();
        builder.Append("enum ").Append(protoEnumName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    option (nanopb_enumopt).long_names = false;");
        builder.AppendLine("    option (nanopb_enumopt).lua_generate = true;");
        builder.AppendLine();
        foreach (var entry in entries)
        {
            builder.Append("    ")
                .Append(entry.Name)
                .Append(" = ")
                .Append(unchecked((int)entry.Crc).ToString(CultureInfo.InvariantCulture))
                .AppendLine(";");
        }

        builder.AppendLine("};");
        return builder.ToString();
    }

    private static List<FsidEntry> BuildEntries(AudioBank bank)
    {
        var entries = new List<FsidEntry>(bank.SoundFiles.Count);
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var sound in bank.SoundFiles)
        {
            var name = NormalizeSoundName(sound.EnumName);
            if (!IdentifierRegex().IsMatch(name))
            {
                throw new InvalidOperationException($"Invalid audio enum name '{sound.EnumName}' after normalization.");
            }

            if (!names.Add(name))
            {
                throw new InvalidOperationException($"Duplicate audio enum name '{name}'.");
            }

            entries.Add(new FsidEntry(name, ComputeSoundCrc(sound.EnumName)));
        }

        return entries;
    }

    [GeneratedRegex(@"^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.CultureInvariant)]
    private static partial Regex IdentifierRegex();

    private readonly record struct FsidEntry(string Name, uint Crc);
}
