#ifndef _CLR_EDGE_AUDIO_FSID_
#define _CLR_EDGE_AUDIO_FSID_

// Generated by Usagi Audio Tool.
static const unsigned int Z_LAST = 4221454624;
static const unsigned int A_FIRST = 567263339;
static const unsigned int spaced_name = 1623057719;
static const unsigned int lowercase = 4265431538;
static const unsigned int EdgeAudio_COUNT = 4;

#endif
