#ifndef _CLR_TEST_AUDIO_FSID_
#define _CLR_TEST_AUDIO_FSID_

// Generated by Usagi Audio Tool.
static const unsigned int LASER_SHOT = 615283986;
static const unsigned int TestAudio_COUNT = 1;

#endif
