param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..\..\..\..").Path
)

$ErrorActionPreference = 'Stop'

$toolProject = Join-Path $RepoRoot 'Tools\Source\UsagiTools\src\Usagi.AudioToolCli\Usagi.AudioToolCli.csproj'
$outDir = Join-Path $PSScriptRoot 'out'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Remove-Item -Path (Join-Path $outDir '*') -Force -ErrorAction SilentlyContinue

function Test-FSIDBuilderFixture {
    param(
        [string]$Name,
        [string]$InputFile,
        [string]$EnumName,
        [string]$IfndefName,
        [string]$ExpectedProto,
        [string]$ExpectedHeader
    )

    $protoOut = Join-Path $outDir "$Name.proto"
    $headerOut = Join-Path $outDir "$Name.h"

    dotnet run --project $toolProject -- -i $InputFile -o $protoOut -e $EnumName -g $IfndefName -p
    if ($LASTEXITCODE -ne 0) {
        throw "Managed FSIDBuilder proto generation for $Name failed with exit code $LASTEXITCODE"
    }

    dotnet run --project $toolProject -- -i $InputFile -o $headerOut -e $EnumName -g $IfndefName
    if ($LASTEXITCODE -ne 0) {
        throw "Managed FSIDBuilder header generation for $Name failed with exit code $LASTEXITCODE"
    }

    $proto = Get-Content -Raw -LiteralPath $protoOut
    $proto = $proto -replace '//  Auto-generated by Usagi Audio Tool at .+', '//  Auto-generated by Usagi Audio Tool at <timestamp>'
    $proto = $proto -replace 'Copyright .* Vitei', 'Copyright (c) Vitei'
    $proto = $proto -replace "`r`n", "`n"
    $expectedProtoText = Get-Content -Raw -LiteralPath $ExpectedProto
    $expectedProtoText = $expectedProtoText -replace "`r`n", "`n"
    if ($proto -ne $expectedProtoText) {
        throw "Generated proto for $Name did not match $(Split-Path -Leaf $ExpectedProto)"
    }

    $header = Get-Content -Raw -LiteralPath $headerOut
    $header = $header -replace "`r`n", "`n"
    $expectedHeaderText = Get-Content -Raw -LiteralPath $ExpectedHeader
    $expectedHeaderText = $expectedHeaderText -replace "`r`n", "`n"
    if ($header -ne $expectedHeaderText) {
        throw "Generated header for $Name did not match $(Split-Path -Leaf $ExpectedHeader)"
    }
}

Test-FSIDBuilderFixture `
    -Name 'minimal' `
    -InputFile (Join-Path $PSScriptRoot 'minimal-legacy.yml') `
    -EnumName 'TestAudio' `
    -IfndefName '_CLR_TEST_AUDIO_FSID_' `
    -ExpectedProto (Join-Path $PSScriptRoot 'expected.proto') `
    -ExpectedHeader (Join-Path $PSScriptRoot 'expected.h')

Test-FSIDBuilderFixture `
    -Name 'edge' `
    -InputFile (Join-Path $PSScriptRoot 'edge-legacy.yml') `
    -EnumName 'EdgeAudio' `
    -IfndefName '_CLR_EDGE_AUDIO_FSID_' `
    -ExpectedProto (Join-Path $PSScriptRoot 'expected-edge.proto') `
    -ExpectedHeader (Join-Path $PSScriptRoot 'expected-edge.h')

Write-Host 'Managed FSIDBuilder smoke fixture matched expected output.'
