param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..\..\..").Path
)

$ErrorActionPreference = 'Stop'

$toolProject = Join-Path $RepoRoot 'Tools\Source\UsagiTools\src\Usagi.AudioToolCli\Usagi.AudioToolCli.csproj'
$fixtureRoot = Join-Path $RepoRoot 'Tools\Tests\AudioToolReverseEngineering\FSIDBuilderSmoke'
$outDir = Join-Path $RepoRoot '..\tools\test-build\AudioToolBuilder'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Remove-Item -LiteralPath (Join-Path $outDir '*') -Force -ErrorAction SilentlyContinue

function Normalize-Proto {
    param([string]$Path)

    $proto = Get-Content -Raw -LiteralPath $Path
    $proto = $proto -replace '//  Auto-generated by Usagi Audio Tool at .+', '//  Auto-generated by Usagi Audio Tool at <timestamp>'
    $proto = $proto -replace 'Copyright .* Vitei', 'Copyright (c) Vitei'
    return $proto -replace "`r`n", "`n"
}

function Normalize-Text {
    param([string]$Path)

    return (Get-Content -Raw -LiteralPath $Path) -replace "`r`n", "`n"
}

function Test-AudioBuilderFixture {
    param(
        [string]$Name,
        [string]$InputFile,
        [string]$EnumName,
        [string]$IfndefName,
        [string]$ExpectedProto,
        [string]$ExpectedHeader
    )

    $protoOut = Join-Path $outDir "$Name.proto"
    $headerOut = Join-Path $outDir "$Name.h"

    dotnet run --project $toolProject --no-restore -- -i $InputFile -o $protoOut -e $EnumName -g $IfndefName -p
    if ($LASTEXITCODE -ne 0) {
        throw "Audio tool proto generation for $Name failed with exit code $LASTEXITCODE"
    }

    dotnet run --project $toolProject --no-restore -- -i $InputFile -o $headerOut -e $EnumName -g $IfndefName
    if ($LASTEXITCODE -ne 0) {
        throw "Audio tool header generation for $Name failed with exit code $LASTEXITCODE"
    }

    if ((Normalize-Proto $protoOut) -ne (Normalize-Text $ExpectedProto)) {
        throw "Generated proto for $Name did not match $(Split-Path -Leaf $ExpectedProto)"
    }

    if ((Normalize-Text $headerOut) -ne (Normalize-Text $ExpectedHeader)) {
        throw "Generated header for $Name did not match $(Split-Path -Leaf $ExpectedHeader)"
    }
}

Test-AudioBuilderFixture `
    -Name 'minimal' `
    -InputFile (Join-Path $fixtureRoot 'minimal-legacy.yml') `
    -EnumName 'TestAudio' `
    -IfndefName '_CLR_TEST_AUDIO_FSID_' `
    -ExpectedProto (Join-Path $fixtureRoot 'expected.proto') `
    -ExpectedHeader (Join-Path $fixtureRoot 'expected.h')

Test-AudioBuilderFixture `
    -Name 'edge' `
    -InputFile (Join-Path $fixtureRoot 'edge-legacy.yml') `
    -EnumName 'EdgeAudio' `
    -IfndefName '_CLR_EDGE_AUDIO_FSID_' `
    -ExpectedProto (Join-Path $fixtureRoot 'expected-edge.proto') `
    -ExpectedHeader (Join-Path $fixtureRoot 'expected-edge.h')

$normalizedYaml = Join-Path $outDir 'minimal.normalized.yml'
dotnet run --project $toolProject --no-restore -- -i (Join-Path $fixtureRoot 'minimal-legacy.yml') -o $normalizedYaml --normalize-yaml
if ($LASTEXITCODE -ne 0) {
    throw "Audio tool YAML normalization failed with exit code $LASTEXITCODE"
}

$normalized = Get-Content -Raw -LiteralPath $normalizedYaml
foreach ($required in @('filterCRC:', 'effectCRCs:', 'roomNameCRC:', 'filters:', 'reverbs:', 'rooms:')) {
    if (!$normalized.Contains($required)) {
        throw "Normalized YAML did not contain expected field $required"
    }
}

$invalidYaml = Join-Path $outDir 'invalid.yml'
@'
AudioBank:
  soundFiles:
    - enumName: 1 invalid
      filename: bad.wav
      volume: -1
'@ | Set-Content -LiteralPath $invalidYaml -NoNewline

dotnet run --project $toolProject --no-restore -- -i $invalidYaml --validate
if ($LASTEXITCODE -eq 0) {
    throw 'Audio tool validation unexpectedly succeeded for invalid YAML.'
}

Write-Host 'Audio tool builder matched legacy FSID fixtures.'
