param(
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..\..\..").Path
)

$ErrorActionPreference = 'Stop'

$ResolvedRepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)
$RepoRoot = $ResolvedRepoRoot
$RepoParent = Split-Path -Parent $RepoRoot
$ToolsRoot = Join-Path $RepoParent 'tools'
if (-not (Test-Path (Join-Path $ToolsRoot 'usagi-dev-env.ps1'))) {
    $ToolsRoot = Join-Path (Split-Path -Parent $RepoParent) 'tools'
}
$ToolsRoot = [System.IO.Path]::GetFullPath($ToolsRoot)
. (Join-Path $ToolsRoot 'usagi-dev-env.ps1')

$RepoRoot = $ResolvedRepoRoot
$env:USAGI_DIR = $RepoRoot
$BuildRoot = Join-Path $ToolsRoot 'test-build\AudioToolParity'
$ProjectRoot = Join-Path $BuildRoot 'Project'
$OutRoot = Join-Path $BuildRoot 'out'
$AudioDir = Join-Path $ProjectRoot 'Data\VPB\Audio'

Remove-Item -LiteralPath $BuildRoot -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $AudioDir, $OutRoot | Out-Null

$LegacyBankYaml = Join-Path $AudioDir 'ProjectAudioLegacy.yml'
@'
AudioBank:
  soundFiles:
    - enumName: PLAYER SHOT
      filename: player_shot
      stream: false
      loop: true
      volume: 0.75
      minDistance: 2.0
      maxDistance: 25.0
      eType: 1
      eFalloff: 1
      pitchRandomisation: 0.1
      dopplerFactor: 0.2
      basePitch: 1.1
      priority: 42
      crossfade: fade_a
      localized: false
      crc: 100
    - enumName: MUSIC_THEME
      filename: music/theme
      stream: true
      loop: false
      volume: 1.0
      minDistance: 1.0
      maxDistance: 1000.0
      eType: 0
      eFalloff: 0
      priority: 128
      crc: 0
    - enumName: Z_LAST
      filename: z_last
      eType: 1
      eFalloff: 0
'@ | Set-Content -Encoding ASCII -LiteralPath $LegacyBankYaml

$CurrentBankYaml = Join-Path $AudioDir 'ProjectAudioCurrent.yml'
@'
AudioBank:
  soundFiles:
    - enumName: PLAYER SHOT
      filename: player_shot
      stream: false
      loop: true
      volume: 0.75
      minDistance: 2.0
      maxDistance: 25.0
      eType: 1
      eFalloff: 1
      pitchRandomisation: 0.1
      dopplerFactor: 0.2
      basePitch: 1.1
      priority: 42
      crossfade: fade_a
      localized: false
      crc: 100
      filterCRC: 200
      effectCRCs:
        - 300
      roomNameCRC: 400
    - enumName: MUSIC_THEME
      filename: music/theme
      stream: true
      loop: false
      volume: 1.0
      minDistance: 1.0
      maxDistance: 1000.0
      eType: 0
      eFalloff: 0
      priority: 128
      crc: 0
      filterCRC: 0
      effectCRCs: []
      roomNameCRC: 0
    - enumName: Z_LAST
      filename: z_last
      eType: 1
      eFalloff: 0
      filterCRC: 0
      effectCRCs: []
      roomNameCRC: 0
  filters:
    - enumName: FILTER_LOW
      crc: 200
      eFilter: 0
      fFrequency: 0.5
      fOneOverQ: 1.25
  reverbs:
    - effectDef:
        eEffectType: 0
        enumName: REVERB_SMALL
        crc: 300
      wetDryMix: 75.0
      reflectionsDelay: 10
      reverbDelay: 50
      roomFilterFreq: 100.0
      roomFilterMain: -3.0
      roomFilterHF: -6.0
      reflectionsGain: 5.0
      reverbGain: 6.0
      decayTime: 1.5
      density: 90.0
      roomSize: 25.0
  rooms:
    - roomName: ROOM_SMALL
      roomCrc: 400
      filterCrc: 200
      effectCrcs:
        - 300
'@ | Set-Content -Encoding ASCII -LiteralPath $CurrentBankYaml

function Normalize-Proto {
    param([string]$Path)

    $proto = Get-Content -Raw -LiteralPath $Path
    $proto = $proto -replace '//  Auto-generated by Usagi Audio Tool at .+', '//  Auto-generated by Usagi Audio Tool at <timestamp>'
    $proto = $proto -replace 'Copyright .* Vitei', 'Copyright (c) Vitei'
    return $proto -replace "`r`n", "`n"
}

function Normalize-Text {
    param([string]$Path)

    return (Get-Content -Raw -LiteralPath $Path) -replace "`r`n", "`n"
}

function Assert-Match {
    param(
        [string]$ExpectedPath,
        [string]$ActualPath,
        [switch]$Proto,
        [string]$Description
    )

    $expected = if ($Proto) { Normalize-Proto $ExpectedPath } else { Normalize-Text $ExpectedPath }
    $actual = if ($Proto) { Normalize-Proto $ActualPath } else { Normalize-Text $ActualPath }
    if ($expected -ne $actual) {
        throw "$Description did not match legacy FSIDBuilder output."
    }
}

$LegacyTool = Join-Path $RepoRoot 'Tools\AudioTool\FSIDBuilder.exe'
$ManagedProject = Join-Path $RepoRoot 'Tools\Source\UsagiTools\src\Usagi.AudioToolCli\Usagi.AudioToolCli.csproj'

$LegacyProto = Join-Path $OutRoot 'legacy.proto'
$LegacyHeader = Join-Path $OutRoot 'legacy.h'
$ManagedProto = Join-Path $OutRoot 'managed.proto'
$ManagedHeader = Join-Path $OutRoot 'managed.h'
$NormalizedYaml = Join-Path $OutRoot 'normalized.yml'
$ManagedNormalizedProto = Join-Path $OutRoot 'managed-normalized.proto'
$CurrentManagedProto = Join-Path $OutRoot 'managed-current.proto'
$CurrentManagedHeader = Join-Path $OutRoot 'managed-current.h'
$LegacyCurrentFailure = Join-Path $OutRoot 'legacy-current-failure.txt'

& $LegacyTool -i $LegacyBankYaml -o $LegacyProto -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_ -p
if ($LASTEXITCODE -ne 0) {
    throw "Legacy FSIDBuilder proto generation failed."
}

& $LegacyTool -i $LegacyBankYaml -o $LegacyHeader -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_
if ($LASTEXITCODE -ne 0) {
    throw "Legacy FSIDBuilder header generation failed."
}

dotnet run --project $ManagedProject --no-restore -- -i $LegacyBankYaml -o $ManagedProto -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_ -p
if ($LASTEXITCODE -ne 0) {
    throw "Managed audio proto generation failed."
}

dotnet run --project $ManagedProject --no-restore -- -i $LegacyBankYaml -o $ManagedHeader -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_
if ($LASTEXITCODE -ne 0) {
    throw "Managed audio header generation failed."
}

Assert-Match -ExpectedPath $LegacyProto -ActualPath $ManagedProto -Proto -Description 'Legacy-compatible proto parity'
Assert-Match -ExpectedPath $LegacyHeader -ActualPath $ManagedHeader -Description 'Legacy-compatible header parity'

dotnet run --project $ManagedProject --no-restore -- -i $LegacyBankYaml -o $NormalizedYaml --normalize-yaml
if ($LASTEXITCODE -ne 0) {
    throw "Managed audio YAML normalization failed."
}

dotnet run --project $ManagedProject --no-restore -- -i $NormalizedYaml -o $ManagedNormalizedProto -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_ -p
if ($LASTEXITCODE -ne 0) {
    throw "Managed normalized audio proto generation failed."
}

Assert-Match -ExpectedPath $LegacyProto -ActualPath $ManagedNormalizedProto -Proto -Description 'Normalized proto parity'

$PreviousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try {
    & $LegacyTool -i $CurrentBankYaml -o (Join-Path $OutRoot 'legacy-current.proto') -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_ -p *> $LegacyCurrentFailure
    $LegacyCurrentExitCode = $LASTEXITCODE
}
finally {
    $ErrorActionPreference = $PreviousErrorActionPreference
}
if ($LegacyCurrentExitCode -eq 0) {
    throw "Legacy FSIDBuilder unexpectedly accepted current full-schema YAML."
}

dotnet run --project $ManagedProject --no-restore -- -i $CurrentBankYaml -o $CurrentManagedProto -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_ -p
if ($LASTEXITCODE -ne 0) {
    throw "Managed current-schema audio proto generation failed."
}

dotnet run --project $ManagedProject --no-restore -- -i $CurrentBankYaml -o $CurrentManagedHeader -e ProjectAudio -g _CLR_PROJECT_AUDIO_FSID_
if ($LASTEXITCODE -ne 0) {
    throw "Managed current-schema audio header generation failed."
}

Write-Host "Audio parity passed for synthetic legacy-compatible bank: $LegacyBankYaml"
Write-Host "Managed current-schema generation passed; legacy rejection captured in $LegacyCurrentFailure"
